/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Gallery {
  'id' : string,
  'status' : GalleryStatus,
  'clientName' : string,
  'name' : string,
  'createdAt' : Time,
}
export type GalleryStatus = { 'closed' : null } |
  { 'open' : null };
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Photo {
  'id' : string,
  'filename' : string,
  'blobId' : ExternalBlob,
  'galleryId' : string,
  'uploadedAt' : Time,
}
export interface PhotoSelection {
  'selectedPhotoIds' : Array<string>,
  'submittedAt' : Time,
  'galleryId' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<[string, ExternalBlob, string], Photo>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Claim photographer access -- any authenticated user can become a photographer
   */
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  /**
   * / Create a new gallery
   */
  'createGallery' : ActorMethod<[string, string], Gallery>,
  'deleteGallery' : ActorMethod<[string], undefined>,
  /**
   * / Admin: Delete a photo from a gallery
   */
  'deletePhoto' : ActorMethod<[string], undefined>,
  /**
   * / Functions related to Invite Links
   */
  'generateInviteCode' : ActorMethod<[], string>,
  /**
   * / Admin: List all galleries
   */
  'getAllGalleries' : ActorMethod<[], Array<Gallery>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Access gallery by invite token (public - no authentication required)
   */
  'getGalleryByInviteToken' : ActorMethod<[string], [Gallery, Array<Photo>]>,
  /**
   * / ADMIN: Get selection for a gallery
   */
  'getGallerySelection' : ActorMethod<[string], [] | [PhotoSelection]>,
  /**
   * / Admin: Get a single gallery with its photos
   */
  'getGalleryWithPhotos' : ActorMethod<[string], [Gallery, Array<Photo>]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  /**
   * / Get invite token for a gallery
   */
  'getInviteToken' : ActorMethod<[string], [] | [string]>,
  /**
   * / Generate/get invite token for a gallery
   */
  'getOrCreateInviteToken' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Check if any admin exists
   */
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  /**
   * / Submit final selection (can only submit once) - public, no authentication required
   */
  'submitSelection' : ActorMethod<[string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];